spring:
  application:
    name: operation-app
  cloud:
    consul:
      host: 192.168.23.128
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        deregister: false
server:
  port: 8106
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#ribbon的超时时间, 防止feign调用超时
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 2 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试